apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: mysql-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi