apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: wordpress
spec:
  maxReplicas: {{.Values.wordpress.hpa.maxReplicas}}
  minReplicas: {{.Values.wordpress.hpa.minReplicas}}
  targetCPUUtilizationPercentage: {{.Values.wordpress.hpa.targetCPUUtilizationPercentage}}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wordpress

