apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: wordpress
spec:
  ports:
    - name: 80-80
      port: {{ .Values.wordpress.service.port }}
      protocol: TCP
      targetPort: {{ .Values.wordpress.service.targetPort }}
  selector:
    app: wordpress
    tier: frontend